"""initial_garage"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_catalog',
    sa.Column('catalog_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('melee_power', sa.Integer(), nullable=False),
    sa.Column('view_distance', sa.Integer(), nullable=False),
    sa.Column('max_health', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('carry_capacity', sa.Integer(), nullable=False),
    sa.CheckConstraint("rarity IN ('common', 'rare', 'epic')"),
    sa.CheckConstraint("slot IN ('torso', 'legs', 'arms', 'head')"),
    sa.CheckConstraint('max_health > 0 AND weight >= 0 AND carry_capacity >= 0'),
    sa.PrimaryKeyConstraint('catalog_key'),
    sa.UniqueConstraint('catalog_key', 'slot')
    )
    op.create_table('pilots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Integer(), nullable=False),
    sa.Column('matches_finished', sa.Integer(), nullable=False),
    sa.Column('reward_rolls', sa.Integer(), nullable=False),
    sa.Column('rewards_received', sa.Integer(), nullable=False),
    sa.Column('parts_equipped', sa.Integer(), nullable=False),
    sa.Column('rematches_started', sa.Integer(), nullable=False),
    sa.CheckConstraint('xp >= 0 AND level >= 1 AND currency >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_catalog',
    sa.Column('skill_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proc_chance', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("trigger IN ('attack', 'defense')"),
    sa.CheckConstraint('proc_chance BETWEEN 0 AND 1'),
    sa.PrimaryKeyConstraint('skill_key')
    )
    op.create_table('mech_loadouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pilot_id', sa.Uuid(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reactor_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fire_control_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("fire_control_mode IN ('precision', 'neutral', 'impact')"),
    sa.CheckConstraint("reactor_mode IN ('fortified', 'neutral', 'overdrive')"),
    sa.CheckConstraint('slot_index IN (0, 1)'),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'pilot_id'),
    sa.UniqueConstraint('pilot_id', 'slot_index')
    )
    op.create_index(op.f('ix_mech_loadouts_pilot_id'), 'mech_loadouts', ['pilot_id'], unique=False)
    op.create_table('part_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pilot_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('affix_tier', sa.Integer(), nullable=False),
    sa.Column('affix_stat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('affix_value', sa.Integer(), nullable=False),
    sa.CheckConstraint("affix_stat IS NULL OR (slot = 'torso' AND affix_stat = 'health') OR (slot = 'legs' AND affix_stat = 'speed') OR (slot = 'arms' AND affix_stat IN ('accuracy', 'melee_power')) OR (slot = 'head' AND affix_stat = 'view_distance')"),
    sa.CheckConstraint('(affix_tier = 0 AND affix_stat IS NULL AND affix_value = 0) OR (affix_tier BETWEEN 1 AND 3 AND affix_stat IS NOT NULL AND affix_value > 0)'),
    sa.ForeignKeyConstraint(['catalog_key', 'slot'], ['part_catalog.catalog_key', 'part_catalog.slot'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'pilot_id', 'slot')
    )
    op.create_index(op.f('ix_part_instances_pilot_id'), 'part_instances', ['pilot_id'], unique=False)
    op.create_table('pending_skill_choices',
    sa.Column('pilot_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.CheckConstraint('level >= 2'),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('pilot_id', 'level')
    )
    op.create_table('pilot_skills',
    sa.Column('pilot_id', sa.Uuid(), nullable=False),
    sa.Column('skill_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.ForeignKeyConstraint(['skill_key'], ['skill_catalog.skill_key'], ),
    sa.PrimaryKeyConstraint('pilot_id', 'skill_key')
    )
    op.create_table('skill_choice_rules',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('skill_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required_skill_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('level >= 2'),
    sa.ForeignKeyConstraint(['required_skill_key'], ['skill_catalog.skill_key'], ),
    sa.ForeignKeyConstraint(['skill_key'], ['skill_catalog.skill_key'], ),
    sa.PrimaryKeyConstraint('level', 'skill_key')
    )
    op.create_table('loadout_parts',
    sa.Column('loadout_id', sa.Uuid(), nullable=False),
    sa.Column('slot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pilot_id', sa.Uuid(), nullable=False),
    sa.Column('part_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['loadout_id', 'pilot_id'], ['mech_loadouts.id', 'mech_loadouts.pilot_id'], ),
    sa.ForeignKeyConstraint(['part_id', 'pilot_id', 'slot'], ['part_instances.id', 'part_instances.pilot_id', 'part_instances.slot'], ),
    sa.PrimaryKeyConstraint('loadout_id', 'slot'),
    sa.UniqueConstraint('part_id')
    )
    op.create_table('loadout_weapons',
    sa.Column('loadout_id', sa.Uuid(), nullable=False),
    sa.Column('hand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weapon_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('cost_ap', sa.Integer(), nullable=False),
    sa.Column('attack_range', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.CheckConstraint("hand IN ('left', 'right')"),
    sa.CheckConstraint("weapon_type IN ('melee', 'ranged')"),
    sa.CheckConstraint('accuracy BETWEEN 0 AND 100'),
    sa.CheckConstraint('damage > 0 AND cost_ap > 0 AND attack_range > 0 AND weight >= 0'),
    sa.ForeignKeyConstraint(['loadout_id'], ['mech_loadouts.id'], ),
    sa.PrimaryKeyConstraint('loadout_id', 'hand')
    )
    part_catalog = sa.table(
        "part_catalog",
        sa.column("catalog_key", sa.String),
        sa.column("slot", sa.String),
        sa.column("name", sa.String),
        sa.column("rarity", sa.String),
        sa.column("health", sa.Integer),
        sa.column("speed", sa.Integer),
        sa.column("accuracy", sa.Integer),
        sa.column("melee_power", sa.Integer),
        sa.column("view_distance", sa.Integer),
        sa.column("max_health", sa.Integer),
        sa.column("weight", sa.Integer),
        sa.column("carry_capacity", sa.Integer),
    )
    op.bulk_insert(
        part_catalog,
        [
            {"catalog_key": "default_torso", "slot": "torso", "name": "Лёгкий корпус", "rarity": "common", "health": 15, "speed": 0, "accuracy": 0, "melee_power": 0, "view_distance": 0, "max_health": 10, "weight": 6, "carry_capacity": 0},
            {"catalog_key": "default_legs", "slot": "legs", "name": "Стандартные ноги", "rarity": "common", "health": 0, "speed": 5, "accuracy": 0, "melee_power": 0, "view_distance": 0, "max_health": 10, "weight": 5, "carry_capacity": 25},
            {"catalog_key": "default_arms", "slot": "arms", "name": "Стандартные руки", "rarity": "common", "health": 0, "speed": 0, "accuracy": 87, "melee_power": 2, "view_distance": 0, "max_health": 10, "weight": 4, "carry_capacity": 0},
            {"catalog_key": "default_head", "slot": "head", "name": "Стандартная электроника", "rarity": "common", "health": 0, "speed": 0, "accuracy": 0, "melee_power": 0, "view_distance": 5, "max_health": 10, "weight": 3, "carry_capacity": 0},
            {"catalog_key": "steelman_torso", "slot": "torso", "name": "Тяжёлый корпус «Голем»", "rarity": "rare", "health": 19, "speed": 0, "accuracy": 0, "melee_power": 0, "view_distance": 0, "max_health": 10, "weight": 10, "carry_capacity": 0},
            {"catalog_key": "steelman_legs", "slot": "legs", "name": "Усиленные сервоприводы", "rarity": "rare", "health": 0, "speed": 4, "accuracy": 0, "melee_power": 0, "view_distance": 0, "max_health": 10, "weight": 8, "carry_capacity": 42},
            {"catalog_key": "steelman_arms", "slot": "arms", "name": "Ударный привод «Молот»", "rarity": "rare", "health": 0, "speed": 0, "accuracy": 85, "melee_power": 4, "view_distance": 0, "max_health": 10, "weight": 6, "carry_capacity": 0},
            {"catalog_key": "steelman_head", "slot": "head", "name": "Штурмовая электроника", "rarity": "rare", "health": 0, "speed": 0, "accuracy": 0, "melee_power": 0, "view_distance": 4, "max_health": 10, "weight": 4, "carry_capacity": 0},
            {"catalog_key": "fireworks_torso", "slot": "torso", "name": "Лёгкий корпус «Стриж»", "rarity": "rare", "health": 11, "speed": 0, "accuracy": 0, "melee_power": 0, "view_distance": 0, "max_health": 10, "weight": 4, "carry_capacity": 0},
            {"catalog_key": "fireworks_legs", "slot": "legs", "name": "Манёвренные ноги «Вихрь»", "rarity": "rare", "health": 0, "speed": 6, "accuracy": 0, "melee_power": 0, "view_distance": 0, "max_health": 10, "weight": 3, "carry_capacity": 24},
            {"catalog_key": "fireworks_arms", "slot": "arms", "name": "Прицельный привод «Соколиный глаз»", "rarity": "rare", "health": 0, "speed": 0, "accuracy": 85, "melee_power": 0, "view_distance": 0, "max_health": 10, "weight": 3, "carry_capacity": 0},
            {"catalog_key": "fireworks_head", "slot": "head", "name": "Дальномерная электроника «Горизонт»", "rarity": "rare", "health": 0, "speed": 0, "accuracy": 0, "melee_power": 0, "view_distance": 7, "max_health": 10, "weight": 3, "carry_capacity": 0},
            {"catalog_key": "strikeforce_torso", "slot": "torso", "name": "Облегчённый каркас «Копьё»", "rarity": "rare", "health": 9, "speed": 0, "accuracy": 0, "melee_power": 0, "view_distance": 0, "max_health": 10, "weight": 3, "carry_capacity": 0},
            {"catalog_key": "strikeforce_legs", "slot": "legs", "name": "Опорная платформа «Такт»", "rarity": "rare", "health": 0, "speed": 3, "accuracy": 0, "melee_power": 0, "view_distance": 0, "max_health": 10, "weight": 9, "carry_capacity": 40},
            {"catalog_key": "strikeforce_arms", "slot": "arms", "name": "Привод наведения рейлгана", "rarity": "rare", "health": 0, "speed": 0, "accuracy": 78, "melee_power": 0, "view_distance": 0, "max_health": 10, "weight": 4, "carry_capacity": 0},
            {"catalog_key": "strikeforce_head", "slot": "head", "name": "Баллистический вычислитель", "rarity": "rare", "health": 0, "speed": 0, "accuracy": 0, "melee_power": 0, "view_distance": 6, "max_health": 10, "weight": 4, "carry_capacity": 0},
        ],
    )
    skill_catalog = sa.table(
        "skill_catalog",
        sa.column("skill_key", sa.String),
        sa.column("name", sa.String),
        sa.column("trigger", sa.String),
        sa.column("proc_chance", sa.Float),
        sa.column("description", sa.String),
    )
    op.bulk_insert(
        skill_catalog,
        [
            {"skill_key": "accurate_shot", "name": "Точный выстрел", "trigger": "attack", "proc_chance": 0.15, "description": "Шанс на атаку: +15 к точности для текущего выстрела."},
            {"skill_key": "heavy_strike", "name": "Усиленный удар", "trigger": "attack", "proc_chance": 0.15, "description": "Шанс на атаку: +3 к силе удара для текущей атаки ближнего боя."},
            {"skill_key": "combat_impulse", "name": "Боевой импульс", "trigger": "attack", "proc_chance": 0.12, "description": "Шанс, что текущая атака не потратит очки действия."},
            {"skill_key": "dodge", "name": "Уклонение", "trigger": "defense", "proc_chance": 0.15, "description": "Шанс полностью избежать входящего удара или выстрела."},
        ],
    )
    skill_choice_rules = sa.table(
        "skill_choice_rules",
        sa.column("level", sa.Integer),
        sa.column("skill_key", sa.String),
        sa.column("required_skill_key", sa.String),
    )
    op.bulk_insert(
        skill_choice_rules,
        [
            {"level": 2, "skill_key": "accurate_shot", "required_skill_key": None},
            {"level": 2, "skill_key": "heavy_strike", "required_skill_key": None},
            {"level": 3, "skill_key": "combat_impulse", "required_skill_key": "accurate_shot"},
            {"level": 3, "skill_key": "dodge", "required_skill_key": "heavy_strike"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loadout_weapons')
    op.drop_table('loadout_parts')
    op.drop_table('skill_choice_rules')
    op.drop_table('pilot_skills')
    op.drop_table('pending_skill_choices')
    op.drop_index(op.f('ix_part_instances_pilot_id'), table_name='part_instances')
    op.drop_table('part_instances')
    op.drop_index(op.f('ix_mech_loadouts_pilot_id'), table_name='mech_loadouts')
    op.drop_table('mech_loadouts')
    op.drop_table('skill_catalog')
    op.drop_table('pilots')
    op.drop_table('part_catalog')
    # ### end Alembic commands ###
