"""match_rewards"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('finalized', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_participants',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('pilot_id', sa.Uuid(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.CheckConstraint('team IN (1, 2)'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'pilot_id')
    )
    op.create_table('match_rewards',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('pilot_id', sa.Uuid(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Uuid(), nullable=True),
    sa.Column('chance', sa.Float(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part_instances.id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'pilot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_rewards')
    op.drop_table('match_participants')
    op.drop_table('matches')
    # ### end Alembic commands ###
