from enum import Enum


class CELL_TYPE(Enum):
    WALL = " # "
    EMPTY = "   "
    START_TEAM_1 = " S1 "
    START_TEAM_2 = " S2 "
    CHEST = " C "
    ENEMY = " E "
    EXIT = " X "
    PLAYER = " P "


class Accuracy:
    DEFAULT_PLAYER_STATS_ACCURACY = 87
    DEFAULT_ENEMY_STATS_ACCURACY = 78
    DEFAULT_PLAYER_MELEE_WEAPON_ACCURACY = 97
    DEFAULT_PLAYER_RANGED_WEAPON_ACCURACY = 86
    DEFAULT_ENEMY_MELEE_WEAPON_ACCURACY = 93
    DEFAULT_ENEMY_RANGED_WEAPON_ACCURACY = 80
